### ISSUE TITLE
Nexus5X等宽屏手机上错位

### ISSUE THREAD

**Issue by pengyuwei** [GzhiYi/mp-calendar#3]
真机、模拟器都可以重现
<img width="425" alt="bug3" src="https://user-images.githubusercontent.com/1535830/132784236-daeb1d26-a949-4e03-8a65-e368e89b15d3.png">

**Comment by pengyuwei** [comment]
提错了，删除吧

**Comment by GzhiYi** [comment]
可以手动调一下宽度？我之前没有对多机型进行验证，目前上班linux上开发不大方便调试。

**Comment by pengyuwei** [comment]
上述修改在iPhoneXS（分辨率2436x1125）依然存在问题。
想根本解决，需要修改日历的flex布局方式，目前使用固定宽高和自动换行，很容易引发适配问题。
建议修改成固定7个元素之后强制换行，7个元素之内nowrap，这样才能根本解决问题。（我css不太熟，有空研究下。）

**Comment by pengyuwei** [comment]
a992f9557849823544e7228d5954af1a6f9df1ad 解决了本issue。
开发环境全部通过后，发现在部分真机上可能还是存在问题，这个时候可以删除calendar样式里的width。
```
.calendar {
  /* width: 90%; */
```
这样修改后，我手头的真机已经都没有问题了。

**Comment by GzhiYi** [comment]
给力的，昨晚打球忘记了，还想看看[doge]
